# Kite pnl project

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
data = pd.read_csv("orders (1).csv")
data

FileNotFoundError: [Errno 2] No such file or directory: 'orders (1).csv'

In [50]:
data = data[(data["Product"]=="MIS") & (data["Status"]=="COMPLETE")]
data

              Time  Type  Instrument Product       Qty.  Avg. price    Status
1   16/12/21 15:08   BUY    ASHOKLEY     MIS  1000/1000      125.70  COMPLETE
3   16/12/21 14:13   BUY  TATAMOTORS     MIS    250/250      490.55  COMPLETE
5   16/12/21 13:21  SELL  TATAMOTORS     MIS    250/250      492.10  COMPLETE
7   16/12/21 12:39  SELL    ASHOKLEY     MIS  1000/1000      125.96  COMPLETE
8   16/12/21 12:29   BUY    ASHOKLEY     MIS  2000/2000      125.70  COMPLETE
9   16/12/21 11:22  SELL    ASHOKLEY     MIS  2000/2000      125.95  COMPLETE
11  16/12/21 10:46  SELL    ASHOKLEY     MIS  2000/2000      125.95  COMPLETE
12  16/12/21 10:24   BUY    ASHOKLEY     MIS  1000/1000      125.60  COMPLETE
13  16/12/21 10:23   BUY    ASHOKLEY     MIS  1000/1000      125.65  COMPLETE

1) Different types of charges for Individual trade

In [51]:
data["Qty."] = data["Qty."].str.split("/").str[0].astype(int)
data

              Time  Type  Instrument Product  Qty.  Avg. price    Status
1   16/12/21 15:08   BUY    ASHOKLEY     MIS  1000      125.70  COMPLETE
3   16/12/21 14:13   BUY  TATAMOTORS     MIS   250      490.55  COMPLETE
5   16/12/21 13:21  SELL  TATAMOTORS     MIS   250      492.10  COMPLETE
7   16/12/21 12:39  SELL    ASHOKLEY     MIS  1000      125.96  COMPLETE
8   16/12/21 12:29   BUY    ASHOKLEY     MIS  2000      125.70  COMPLETE
9   16/12/21 11:22  SELL    ASHOKLEY     MIS  2000      125.95  COMPLETE
11  16/12/21 10:46  SELL    ASHOKLEY     MIS  2000      125.95  COMPLETE
12  16/12/21 10:24   BUY    ASHOKLEY     MIS  1000      125.60  COMPLETE
13  16/12/21 10:23   BUY    ASHOKLEY     MIS  1000      125.65  COMPLETE

In [52]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 1 to 13
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Time        9 non-null      object
 1   Type        9 non-null      object
 2   Instrument  9 non-null      object
 3   Product     9 non-null      object
 4   Qty.        9 non-null      int64
 5   Avg. price  9 non-null      float64
 6   Status      9 non-null      object
dtypes: float64(1), int64(1), object(5)
memory usage: 576.0+ bytes

In [53]:
data["Turnover"]= data["Avg. price"]*data["Qty."].round(2)
data

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0

In [54]:
data["Brokerage"] = (data["Turnover"]*0.03/100).round(2)
data

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,37.71
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,36.79
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,36.91
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,37.79
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,75.42
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,75.57
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,75.57
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,37.68
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,37.70

In [55]:
data["Brokerage"] = data["Brokerage"].clip(upper=20)
data

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20.0
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20.0
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20.0
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20.0
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20.0
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20.0
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20.0

In [56]:
data["STT/CTT"] = (data["Turnover"] * 0.025 / 100 * (data["Type"] == "SELL")).round(2)
data

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20.0,0.00
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20.0,0.00
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20.0,30.76
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20.0,31.49
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20.0,0.00
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20.0,0.00
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20.0,0.00

In [57]:
data["ETC"] = (data["Turnover"]*0.00307/100).round(2)
data

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20.0,0.00,3.86
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20.0,0.00,3.76
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20.0,30.76,3.78
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20.0,31.49,3.87
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20.0,0.00,7.72
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98,7.73
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98,7.73
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20.0,0.00,3.86
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20.0,0.00,3.86

In [58]:
data["SEBI"] = (data["Turnover"]*10/10000000).round(2)
data

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC,SEBI
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20.0,0.00,3.86,0.13
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20.0,0.00,3.76,0.12
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20.0,30.76,3.78,0.12
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20.0,31.49,3.87,0.13
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20.0,0.00,7.72,0.25
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98,7.73,0.25
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98,7.73,0.25
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20.0,0.00,3.86,0.13
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20.0,0.00,3.86,0.13

In [59]:
data["Stamp charges"] = (data["Turnover"] * 0.003/100 * (data["Type"] == "BUY")).round(2)
data

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC,SEBI,Stamp charges
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20.0,0.00,3.86,0.13,3.77
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20.0,0.00,3.76,0.12,3.68
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20.0,30.76,3.78,0.12,0.00
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20.0,31.49,3.87,0.13,0.00
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20.0,0.00,7.72,0.25,7.54
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98,7.73,0.25,0.00
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98,7.73,0.25,0.00
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20.0,0.00,3.86,0.13,3.77
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20.0,0.00,3.86,0.13,3.77

In [60]:
data["GST"] = ((data["Brokerage"] + data["SEBI"] + data["ETC"]) *18/100).round(2)
data

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC,SEBI,Stamp charges,GST
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20.0,0.00,3.86,0.13,3.77,4.32
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20.0,0.00,3.76,0.12,3.68,4.30
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20.0,30.76,3.78,0.12,0.00,4.30
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20.0,31.49,3.87,0.13,0.00,4.32
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20.0,0.00,7.72,0.25,7.54,5.03
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98,7.73,0.25,0.00,5.04
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98,7.73,0.25,0.00,5.04
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20.0,0.00,3.86,0.13,3.77,4.32
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20.0,0.00,3.86,0.13,3.77,4.32

In [61]:
data["Total charges"] = ((data["GST"] + data["Brokerage"] + data["SEBI"] + data["ETC"] + data["STT/CTT"] + data["Stamp charges"])).round(2)
data

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC,SEBI,Stamp charges,GST,Total charges
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20.0,0.00,3.86,0.13,3.77,4.32,32.08
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20.0,0.00,3.76,0.12,3.68,4.30,31.86
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20.0,30.76,3.78,0.12,0.00,4.30,58.96
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20.0,31.49,3.87,0.13,0.00,4.32,59.81
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20.0,0.00,7.72,0.25,7.54,5.03,40.54
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98,7.73,0.25,0.00,5.04,96.00
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98,7.73,0.25,0.00,5.04,96.00
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20.0,0.00,3.86,0.13,3.77,4.32,32.08
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20.0,0.00,3.86,0.13,3.77,4.32,32.08

In [62]:
result1 = data
result1

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC,SEBI,Stamp charges,GST,Total charges
1,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20.0,0.00,3.86,0.13,3.77,4.32,32.08
3,16/12/21 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20.0,0.00,3.76,0.12,3.68,4.30,31.86
5,16/12/21 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20.0,30.76,3.78,0.12,0.00,4.30,58.96
7,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20.0,31.49,3.87,0.13,0.00,4.32,59.81
8,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20.0,0.00,7.72,0.25,7.54,5.03,40.54
9,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98,7.73,0.25,0.00,5.04,96.00
11,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20.0,62.98,7.73,0.25,0.00,5.04,96.00
12,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20.0,0.00,3.86,0.13,3.77,4.32,32.08
13,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20.0,0.00,3.86,0.13,3.77,4.32,32.08

2) Stock wise and Type wise analysis with weighted Avg. price & calculated charges

In [63]:
df1 = data.groupby(["Instrument","Type"],as_index=False)[["Qty."]].sum()
df1

   Instrument  Type  Qty.
0    ASHOKLEY   BUY  5000
1    ASHOKLEY  SELL  5000
2  TATAMOTORS   BUY   250
3  TATAMOTORS  SELL   250

In [64]:
df2 = data.groupby(["Instrument","Type"],as_index=False)[["Avg. price"]].mean()
df2

   Instrument  Type  Avg. price
0    ASHOKLEY   BUY  125.662500
1    ASHOKLEY  SELL  125.953333
2  TATAMOTORS   BUY  490.550000
3  TATAMOTORS  SELL  492.100000

In [65]:
result2 = data.groupby(["Instrument","Type"],as_index=False).agg(
    {"Qty.":"sum",
     "Avg. price":"mean",
     "Turnover":"sum",
     "Brokerage":"sum",
     "STT/CTT":"sum",
     "ETC":"sum",
     "SEBI":"sum",
     "Stamp charges":"sum",
     "GST":"sum",
     "Total charges":"sum"})
result2

,Instrument,Type,Qty.,Avg. price,Turnover,Brokerage,STT/CTT,ETC,SEBI,Stamp charges,GST,Total charges
0,ASHOKLEY,BUY,5000,125.662500,628350.0,80.0,0.00,19.30,0.64,18.85,17.99,136.78
1,ASHOKLEY,SELL,5000,125.953333,629760.0,60.0,157.45,19.33,0.63,0.00,14.40,251.81
2,TATAMOTORS,BUY,250,490.550000,122637.5,20.0,0.00,3.76,0.12,3.68,4.30,31.86
3,TATAMOTORS,SELL,250,492.100000,123025.0,20.0,30.76,3.78,0.12,0.00,4.30,58.96

3) Overall Summary of each Stocks  df5 = pd.DataFrame(result["Gross Pnl"])
df5

In [120]:
result = result2.groupby(["Instrument","Type"])["Turnover"].sum().unstack()
result["Gross Pnl"] = result["SELL"] - result["BUY"]
result["Gross Pnl"]

Instrument
ASHOKLEY      1410.0
TATAMOTORS     387.5
Name: Gross Pnl, dtype: float64

In [118]:
Total_charges = result2.groupby("Instrument")["Total charges"].sum()
Total_charges

Instrument
ASHOKLEY      388.59
TATAMOTORS     90.82
Name: Total charges, dtype: float64

In [82]:
net_PnL = result["Gross Pnl"] - Total_charges
net_PnL

Instrument
ASHOKLEY      1021.41
TATAMOTORS     296.68
dtype: float64

In [86]:
Charges_on_Gross_PnL = (Total_charges / result["Gross Pnl"]) *100
Charges_on_Gross_PnL

Instrument
ASHOKLEY      27.559574
TATAMOTORS    23.437419
dtype: float64

In [110]:
result3 = pd.DataFrame([result["Gross Pnl"],Total_charges,net_PnL,Charges_on_Gross_PnL])
result3

Instrument        ASHOKLEY  TATAMOTORS
Gross Pnl      1410.000000  387.500000
Total charges   388.590000   90.820000
Unnamed 0      1021.410000  296.680000
Unnamed 1        27.559574   23.437419

In [125]:
result3.rename(index={"Unnamed 0":"net_PnL","Unnamed 1":"%Charges_on_Gross_PnL"},inplace=True)
result3

Instrument                ASHOKLEY  TATAMOTORS
Gross Pnl              1410.000000  387.500000
Total charges           388.590000   90.820000
net_PnL                1021.410000  296.680000
%Charges_on_Gross_PnL    27.559574   23.437419

In [127]:
result3.T

            Gross Pnl  Total charges  net_PnL  %Charges_on_Gross_PnL
Instrument
ASHOKLEY       1410.0         388.59  1021.41              27.559574
TATAMOTORS      387.5          90.82   296.68              23.437419

In [128]:
with pd.ExcelWriter("kite Pnl.xlsx") as writer:
    result1.to_excel(writer,sheet_name="charges for Individual trade",index= False)
    result2.to_excel(writer,sheet_name="Stock Analysis",index= False)
    result3.to_excel(writer,sheet_name="Overall Summary",index= False)